version: "3.8"
services:
  frontend:
    image: 380283976045.dkr.ecr.us-east-1.amazonaws.com/pokepain-frontend:latest
    build: 
      context: frontend
      dockerfile: /Dockerfile.aws
    ports:
      - 8080:8080
    depends_on:
      - backend
  backend:
    image: 380283976045.dkr.ecr.us-east-1.amazonaws.com/pokepain-backend:latest
    build: ./backend
    ports:
      - 8001:8001
    environment:
      NODE_ENV: aws
      POKEDEX_API_PORT: 8001
      POKEDEX_MONGO_HOST: database
      POKEDEX_MONGO_PORT: 27017
      POKEDEX_MONGO_NAME: pokedex
    depends_on:
      - database
    volumes:
      - pokepain:/data/backend
  database:
    image: public.ecr.aws/docker/library/mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - pokepain:/data/db

volumes:
  pokepain: