version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 9999:8080
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 8001:8001
    environment:
      POKEDEX_API_PORT: 8001
      POKEDEX_MONGO_HOST: database
      POKEDEX_MONGO_PORT: 27017
      POKEDEX_MONGO_NAME: pokedex
    depends_on:
      - database
    volumes:
      - pokepain:/data/backend
  database:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - pokepain:/data/db

volumes:
  pokepain: